config/routes.rb
Rails.application.routes.draw do

  root to: 'public/homes#top'
  get 'about' => 'public/homes#about'

  scope module: :public do
    get 'customers/my_page', to: 'customers#show'
    get 'customers/my_page/edit', to: 'customers#edit'
    patch 'customers/my_page', to: 'customers#update'
    get 'customers/confirm', to: 'customers#confirm'
    patch 'customers/unsubscribe', to: 'customers#unsubscribe'
    delete 'cart_items/destroy_all', to: 'cart_items#destroy_all'
    get 'orders/confirm', to: 'orders#confirm'
    post 'orders/confirm', to: 'orders#confirm'
    get 'orders/complete', to: 'orders#complete'
    resources :items, only:[:index, :show]
    resources :cart_items, only:[:index, :create, :update, :destroy]
    resources :orders, only:[:new, :create, :index, :show]
    resources :addresses, only:[:index, :create, :edit, :update, :destroy]
  end

  namespace :admin do
    get '/' => 'homes#top', as: :root
    resources :genres, only:[:index, :create, :edit, :update]
    resources :items, only:[:index, :new, :create, :show, :edit, :update]
    resources :customers, only:[:index, :show, :edit, :update]
    resources :order_items, only:[:update]
    resources :orders, only:[:update, :edit]
  end


# devise顧客用
# URL /customers/sign_in ...
devise_for :customers, skip: [:passwords], controllers: {
  registrations: "public/registrations",
  sessions: 'public/sessions'
}

# devise管理者用
# URL /admin/sign_in ...
devise_for :admin, skip: [:registrations, :passwords], controllers: {
  sessions: "admin/sessions"
}
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :addresses
  has_many :cart_items
  has_many :orders

  with_options presence: true do
    validates :last_name
    validates :first_name
    validates :last_name_kana
    validates :first_name_kana
    validates :email
    validates :encrypted_password
    validates :postal_code
    validates :address
    validates :telephone_number
  end

  def address_display
    "〒" + postal_code + ' ' + address
  end

end

app/controllers/admin/customers_controller.rb
class Admin::CustomersController < ApplicationController
  def show
    @customer = Customer.find(params[:id])
  end

  def index
    @customers = Customer.page(params[:page])
  end

  def edit
    @customer = Customer.find(params[:id])
  end

  def update
    @customer = Customer.find(params[:id])
    if @customer.update(customer_params)
      redirect_to admin_customer_path(@customer)
      flash[:notice] = "更新が完了しました。"
    else
      render 'edit'
    end
  end

  private

  def customer_params
    params.require(:customer).permit(:last_name, :first_name, :last_name_kana, :first_name_kana, :postal_code, :address, :telephone_number, :email, :is_deleted)
  end
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/views/admin/customers/edit.html.erb
<!--nagano_cake admin/customer/edit-->
<body>
  <main>
    <%= render 'layouts/admin_header_template' %>

    <% if @customer.errors.any? %>
    <div id="error_explanation">
        <h2><%= pluralize(@customer.errors.count, "error") %>prohibited this obj from being saved:</h2>
        <ul>
        <% @customer.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
    </div>
    <% end %>

    <div class="container">
      <div class="row">
        <h1 class="mb-5"><%= @customer.last_name %><%= @customer.first_name %> さんの会員情報編集</h1>
        <div class="col-md-10">
          <%= form_with model: @customer, url: admin_customer_path(@customer), method: :patch do |f| %>
          <div class="form-group">
            <div class="form-inline mb-5">
              <%= f.label :id, "会員ID", class: "col-sm-2 justify-content-start" %>
              <%= @customer.id %>
            </div>

            <div class="form-inline mb-5">
              <%= f.label :name, "氏名", class: "col-sm-2 justify-content-start" %>
              <%= f.text_field :last_name, class: "form-control mr-3" %>
              <%= f.text_field :first_name, class: "form-control" %>
            </div>

            <div class="form-inline mb-5">
              <%= f.label :last_name_kana, "フリガナ", class: "col-sm-2 justify-content-start" %>
              <%= f.text_field :last_name_kana, class: "form-control mr-3" %>
              <%= f.text_field :first_name_kana, class: "form-control" %>
            </div>


            <div class="form-inline mb-5">
              <%= f.label :postal_code, "郵便番号", class: "col-sm-2 justify-content-start" %><br />
              <%= f.text_field :postal_code, class: "form-control" %>
            </div>

            <div class="form-inline mb-5">
              <%= f.label :address, "住所", class: "col-sm-2 justify-content-start" %><br />
              <%= f.text_area :address, class: "form-control w-75" %>
            </div>

            <div class="form-inline mb-5">
              <%= f.label :telephone_number, "電話番号", class: "col-sm-2 justify-content-start" %><br />
              <%= f.text_field :telephone_number, class: "form-control" %>
            </div>

            <div class="form-inline mb-5">
              <%= f.label :email, "メールアドレス", class: "col-sm-2 justify-content-start" %>
              <%= f.email_field :email, class: "form-control w-75" %>
            </div>

            <div class="form-inline mb-5">
              <%= f.label :is_deleted, "会員ステータス", class: "col-sm-2 justify-content-start" %><br>
              <%= f.radio_button :is_deleted, false %>
              <%= f.label :is_deleted, "有効", value: "false", class: "mr-3"  %><br>
              <%= f.radio_button :is_deleted, true %>
              <%= f.label :is_deleted, "退会", value: "true" %>
            </div>

            <div class="col-3 offset-2">
              <%= f.submit "変更を保存", class: "btn btn-success btn-lg" %>
            </div>
          </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</main>
 <%= render 'layouts/footer_template' %>
</body>

app/views/admin/customers/index.html.erb
<body>
  <%= render 'layouts/admin_header_template' %>
  <main>
    <div class="container">
      <h1>会員一覧</h1>
      <div class="row mt-5">
        <div class="w-100 mx-auto col-10 align-items-center">
          <table class="table table-bordered">
            <thead class="table-secondary">
              <tr>
                <th>会員ID</th>
                <th>氏名</th>
                <th>メールアドレス</th>
                <th>ステータス</th>
              </tr>
            </thead>
            <tbody>
              <% @customers.each do |customer| %>
              <tr>
                <td><%= customer.id %></td>
                <td>
                  <%= link_to(admin_customer_path(customer)) do %>
                    <%= customer.last_name %> <%= customer.first_name %>
                  <% end %>
                </td>
                <td><%= customer.email %></td>
                <td>
                  <% if customer.is_deleted == true %>
                    <span class="text-secondary">退会</span>
                  <% else %>
                    <span class="text-success">有効</span>
                  <% end %>
                </td>
              </tr>
              <% end %>
            </tbody>
          </table>
        </div>
      </div>
      <%= paginate @customers %>
    </div>
  </main>
  <%= render 'layouts/footer_template' %>
</body>

app/views/admin/customers/show.html.erb
<body>
  <%= render 'layouts/admin_header_template'%>
  <main>
    <div class="container">
      <%= render 'layouts/flash' %>
      <h1 class="mb-5"><%= @customer.last_name %><%= @customer.first_name %> さんの会員詳細</h1>
      <div class="row">
        <div class="col-md-10">
          <table class="table table-borderless">
            <tbody>
              <tr>
                <td>会員ID</td>
                <td><%= @customer.id %></td>
              </tr>
              <tr>
                <td>氏名</td>
                <td><%= @customer.last_name %> <%= @customer.first_name %></td>
              </tr>
              <tr>
                <td>フリガナ</td>
                <td><%= @customer.last_name_kana %> <%= @customer.first_name_kana %></td>
              </tr>
              <tr>
                <td>郵便番号</td>
                <td><%= @customer.postal_code %></td>
              </tr>
              <tr>
                <td>住所</td>
                <td><%= @customer.address %></td>
              </tr>
              <tr>
                <td>電話番号</td>
                <td><%= @customer.telephone_number %></td>
              </tr>
              <tr>
                <td>メールアドレス</td>
                <td><%= @customer.email %></td>
              </tr>
              <tr>
                <td>会員ステータス</td>
                <td>
                  <% if @customer.is_deleted == true %>
                    <span class="text-secondary">退会</span>
                  <% else %>
                    <span class="text-success">有効</span>
                  <% end %>
                </td>
              </tr>
            </tbody>
          </table>
        </div>
      </div>

      <div class="row">
        <div class="col-5 offset-4 d-flex">
            <div class="d-inline"><%= link_to "編集する", edit_admin_customer_path(@customer.id), class: "btn btn-success" %></div>
            <div class="d-inline ml-5"><%= link_to "注文履歴一覧を見る", admin_root_path(customer_id: @customer.id), class: "btn btn-primary ml-6" %></div>
        </div>
      </div>
    </div>
  </main>
  <%= render 'layouts/footer_template' %>
</body>