config/routes.rb
Rails.application.routes.draw do

  root to: 'public/homes#top'
  get 'about' => 'public/homes#about'

  scope module: :public do
    get 'customers/my_page', to: 'customers#show'
    get 'customers/my_page/edit', to: 'customers#edit'
    patch 'customers/my_page', to: 'customers#update'
    get 'customers/confirm', to: 'customers#confirm'
    patch 'customers/unsubscribe', to: 'customers#unsubscribe'
    delete 'cart_items/destroy_all', to: 'cart_items#destroy_all'
    get 'orders/confirm', to: 'orders#confirm'
    post 'orders/confirm', to: 'orders#confirm'
    get 'orders/complete', to: 'orders#complete'
    resources :items, only:[:index, :show]
    resources :cart_items, only:[:index, :create, :update, :destroy]
    resources :orders, only:[:new, :create, :index, :show]
    resources :addresses, only:[:index, :create, :edit, :update, :destroy]
  end

  namespace :admin do
    get '/' => 'homes#top', as: :root
    resources :genres, only:[:index, :create, :edit, :update]
    resources :items, only:[:index, :new, :create, :show, :edit, :update]
    resources :customers, only:[:index, :show, :edit, :update]
    resources :order_items, only:[:update]
    resources :orders, only:[:update, :edit]
  end


# devise顧客用
# URL /customers/sign_in ...
devise_for :customers, skip: [:passwords], controllers: {
  registrations: "public/registrations",
  sessions: 'public/sessions'
}

# devise管理者用
# URL /admin/sign_in ...
devise_for :admin, skip: [:registrations, :passwords], controllers: {
  sessions: "admin/sessions"
}
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :customer
  has_many :order_items
  enum payment_method: {credit_card: 0, transfer: 1 }
  enum order_status: {pending: 0, payment_confirmation: 1, making: 2, preparing_shipment: 3, completed: 4}

  def address_display
    "〒" + postal_code + ' ' + address + ' ' + name
  end

  # def item_total
    # @total = 0
    # current_customer.cart_items.each do |cart_item|
      # sub_total = cart_item.amount * cart_item.item.with_tax_price
      # @total += sub_total
    # end
    # return @total
  # end

  # def subtotal (cart_itemのmodel)
    # item.with_tax_price * amount
  # end


  # def with_tax_price (itemのmodel)
    # (price * 1.1).floor

  # def total_calc
    # sub_total = 0
    # @cart_items.each do |c|
      # sub_total = c.amount * c.item.with_tax_price
      # total += sub_total
    # end
    # return total
  # end

end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < ApplicationController
  def edit
    @order = Order.find(params[:id])
    @order_items = @order.order_items
  end

  def update
    @order = Order.find(params[:id])
    if @order.update(order_params)
      redirect_to edit_admin_order_path(@order)
      @order = Order.find(params[:id])
      # binding.pry
      if @order.order_status == "payment_confirmation" #なぜstring？？数字はkeyだから？
        @order.order_items.each do |order_item|
          order_item.update(making_status: 1) #こっちはなぜ数字？
        end
      end
      flash[:notice] = "注文ステータスの更新が完了しました"
    else
      render 'edit'
      flash[:alert] = "注文ステータスの更新ができませんでした"
    end
  end

  private
    def order_params
      params.require(:order).permit(:order_status)
    end
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/views/admin/orders/edit.html.erb
<!--admin/orders/edit-->
<body>
  <%= render 'layouts/admin_header_template' %>
  <main>
    <div class="container">
      <%= render 'layouts/flash' %>
      <h1>注文履歴詳細</h1>
      <div class="row">
        <div class="col-10">
          <table class="table table-borderless mb-3">
            <tbody>
              <tr>
                <td>購入者</td>
                <td>
                  <%= link_to(admin_customer_path(@order.customer_id)) do %>
                    <%= @order.customer.last_name %><%= @order.customer.first_name %>
                  <% end %>
                </td>
              </tr>
              <tr>
                <td>注文日</td>
                <td><%= @order.created_at %></td>
              </tr>
              <tr>
                <td>配送先</td>
                <td>
                  〒<%= @order.postal_code %>
                   <%= @order.address %><br>
                  <%= @order.name %>
                </td>
              </tr>
              <tr>
                <td>支払い方法</td>
                <td><%= @order.payment_method_i18n %></td>
              </tr>
              <tr>
                <td>注文ステータス</td>
                <td>
                  <%= form_with model: @order, url: admin_order_path(@order), method: :patch do |f| %>
                    <%= f.select :order_status, Order.order_statuses_i18n.invert %> <!--.inverで表示を日本語・送るvalueを英語にする-->
                    <%= f.submit "更新", class: "btn btn-success ml-5" %>
                  <% end %>
                </td>
              </tr>
            </tbody>
          </table>
        </div>
      </div>

      <div class="row">
        <div class="col-8">
            <table class="table border-bottom">
              <thead class="table-light">
                <tr>
                  <th>商品名</th>
                  <th>単価（税込）</th>
                  <th>数量</th>
                  <th>小計</th>
                  <th>制作ステータス</th>
                  <th></th>
                </tr>
              </thead>
              <tbody>
                <% @order_items.each do |order_item| %>
                <tr>
                  <td><%= order_item.item.name %></td>
                  <td><%= (order_item.item.price * 1.1).floor %></td>
                  <td><%= order_item.amount %></td>
                  <td><%= sub_total = order_item.item.with_tax_price * order_item.amount %></td>
                  <% @order_item = order_item %>
                  <%= form_with model: @order_item, url: admin_order_item_path(@order_item), method: :patch do |f| %>
                  <td><%= f.select :making_status, OrderItem.making_statuses_i18n.invert %></td>
                  <td><%= f.submit "更新", class: "btn btn-success" %>
                  <% end %>
                  </td>
                </tr>
              <% end %>
              </tbody>
            </table>
        </div>

        <div class="col-3 offset-1">
          <table class="table table-borderless mb-3">
            <tbody>
              <tr>
                <th>商品合計</th>
                <td><%= @order.grand_total - @order.shipping_cost %>円
                </td>
              </tr>
              <tr>
                <th>送料</th>
                <td><%= @order.shipping_cost %>円</td>
              </tr>
              <tr>
                <th>請求金額合計</th>
                <td><%= @order.grand_total %></td>
              </tr>
            </tbody>
          </table>
        </div>

      </div>
    </div>
  </main>
  <%= render 'layouts/footer_template' %>
</body>