config/routes.rb
Rails.application.routes.draw do

  root to: 'public/homes#top'
  get 'about' => 'public/homes#about'

  scope module: :public do
    get 'customers/my_page', to: 'customers#show'
    get 'customers/my_page/edit', to: 'customers#edit'
    patch 'customers/my_page', to: 'customers#update'
    get 'customers/confirm', to: 'customers#confirm'
    patch 'customers/unsubscribe', to: 'customers#unsubscribe'
    delete 'cart_items/destroy_all', to: 'cart_items#destroy_all'
    get 'orders/confirm', to: 'orders#confirm'
    post 'orders/confirm', to: 'orders#confirm'
    get 'orders/complete', to: 'orders#complete'
    resources :items, only:[:index, :show]
    resources :cart_items, only:[:index, :create, :update, :destroy]
    resources :orders, only:[:new, :create, :index, :show]
    resources :addresses, only:[:index, :create, :edit, :update, :destroy]
  end

  namespace :admin do
    get '/' => 'homes#top', as: :root
    resources :genres, only:[:index, :create, :edit, :update]
    resources :items, only:[:index, :new, :create, :show, :edit, :update]
    resources :customers, only:[:index, :show, :edit, :update]
    resources :order_items, only:[:update]
    resources :orders, only:[:update, :edit]
  end


# devise顧客用
# URL /customers/sign_in ...
devise_for :customers, skip: [:passwords], controllers: {
  registrations: "public/registrations",
  sessions: 'public/sessions'
}

# devise管理者用
# URL /admin/sign_in ...
devise_for :admin, skip: [:registrations, :passwords], controllers: {
  sessions: "admin/sessions"
}
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/address.rb
class Address < ApplicationRecord
  belongs_to :customer

  def address_display
    "〒" + postal_code + ' ' + address + ' ' + name
  end
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, #:registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  belongs_to :customer
  belongs_to :item

  def subtotal
    item.with_tax_price * amount
  end
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :addresses
  has_many :cart_items
  has_many :orders

  with_options presence: true do
    validates :last_name
    validates :first_name
    validates :last_name_kana
    validates :first_name_kana
    validates :email
    validates :encrypted_password
    validates :postal_code
    validates :address
    validates :telephone_number
  end

  def address_display
    "〒" + postal_code + ' ' + address
  end

end

app/models/genre.rb
class Genre < ApplicationRecord
  has_many :items

  validates :genre_name, presence: true
end

app/models/item.rb
class Item < ApplicationRecord
  has_one_attached :image
  belongs_to :genre
  has_many :cart_items
  has_many :order_items

  with_options presence: true do
    validates :genre_id
    validates :name
    validates :introduction
    validates :price
  end

  def get_image(width, height)
    unless image.attached?
      file_path = Rails.root.join('app/assets/images/no_icon.jpeg')
      image.attach(io: File.open(file_path), filename: 'default_image.jpg', content_type: 'image/jpeg')
    end
    image.variant(resize_to_fill: [width, height]).processed
  end

  def with_tax_price
    (price * 1.1).floor
  end

end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :customer
  has_many :order_items
  enum payment_method: {credit_card: 0, transfer: 1 }
  enum order_status: {pending: 0, payment_confirmation: 1, making: 2, preparing_shipment: 3, completed: 4}

  def address_display
    "〒" + postal_code + ' ' + address + ' ' + name
  end

  # def item_total
    # @total = 0
    # current_customer.cart_items.each do |cart_item|
      # sub_total = cart_item.amount * cart_item.item.with_tax_price
      # @total += sub_total
    # end
    # return @total
  # end

  # def subtotal (cart_itemのmodel)
    # item.with_tax_price * amount
  # end


  # def with_tax_price (itemのmodel)
    # (price * 1.1).floor

  # def total_calc
    # sub_total = 0
    # @cart_items.each do |c|
      # sub_total = c.amount * c.item.with_tax_price
      # total += sub_total
    # end
    # return total
  # end

end

app/models/order_item.rb
class OrderItem < ApplicationRecord
  belongs_to :order
  belongs_to :item
  enum making_status: {pending: 0, waiting: 1, working: 2, completed: 3 }
end

app/controllers/admin/genres_controller.rb
class Admin::GenresController < ApplicationController
  def index
    @genre = Genre.new
    @genres = Genre.all
  end

  def create
    @genre = Genre.new(genre_params)
    if @genre.save
      redirect_to admin_genres_path
      flash[:notice] = "登録が完了しました"
    else
      @genres = Genre.all
      render 'index'
    end
  end

  def edit
    @genre = Genre.find(params[:id])

  end

  def update
    ＠genre = Genre.find(params[:id])
    ＠genre.update(genre_params)
    redirect_to admin_genres_path
    flash[:notice] = "更新が完了しました"
  end

  private

  def genre_params
    params.require(:genre).permit(:genre_name)
  end
end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
  def top
    @orders = Order.page(params[:page])
    @orders = @orders.where(customer_id: params[:customer_id].to_i) if params[:customer_id].present?
    @customer = Customer.find_by(id: params[:customer_id])
    # where()内のparams[:]の中は@いらない
  end

end

app/controllers/admin/items_controller.rb
#admin/items
class Admin::ItemsController < ApplicationController
  def new
    @item = Item.new
  end

  def create
    @item = Item.new(item_params)
    @item.is_active = true
    if @item.save
      redirect_to admin_item_path(@item)
      flash[:notice] = "登録が完了しました"
    else
      render 'new'
    end
  end

  def index
    @items = Item.page(params[:page])
  end

  def show
    @item = Item.find(params[:id])
  end

  def edit
    @item = Item.find(params[:id])
  end

  def update
    @item = Item.find(params[:id])
    if @item.update(item_params)
      redirect_to admin_item_path(@item)
      flash[:notice] = "更新が完了しました"
    else
      @item = Item.find(params[:id])
      render 'edit'
    end
  end

  private

  def item_params
    params.require(:item).permit(:genre_id, :name, :introduction, :price, :image, :is_active)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_customer!, except: [:top, :about], unless: :admin_url
  before_action :authenticate_admin!, if: :admin_url
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def admin_url
    request.fullpath.include?("/admin")
  end

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:last_name, :first_name, :last_name_kana, :first_name_kana, :postal_code, :address, :telephone_number, :email])
  end

  def after_sign_out_path_for(resource_or_scope)
    if resource_or_scope == :customer
      root_path
    else
      resource_or_scope == :admin
      new_admin_session_path
    end
  end

end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/helpers/admin/order_items_helper.rb
module Admin::OrderItemsHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/admin/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

app/views/layouts/_admin_header_template.html.erb
<header class="public mb-5">
  <nav class="navbar navbar-expand-lg navbar navbar-light" style="background-color: #e3f2fd;">
    <div class="container">
      <a class="navbar-brand" href="/">ながのCAKE</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav ml-auto">
          <% if admin_signed_in? %>
            <li class="nav-item"><%= link_to "商品一覧", admin_items_path, class: "nav-link" %></li>
            <li class="nav-item"><%= link_to "会員一覧", admin_customers_path, class: "nav-link" %></li>
            <li class="nav-item"><%= link_to "注文履歴一覧", admin_root_path, class: "nav-link" %></li>
            <li class="nav-item"><%= link_to "ジャンル一覧", admin_genres_path, class: "nav-link" %></li>
            <li class="nav-item"><%= link_to "ログアウト", destroy_admin_session_path, method: :delete, class: "nav-link" %></li>
          <% end %>
        </ul>
      </div>
    </div>
  </nav>
</header>

app/views/layouts/_flash.html.erb
  <% flash.each do |key, value| %>
    <p><%= value %></p>
  <% end %>

app/views/layouts/_footer_template.html.erb
<footer>
  <div class="container mt-5">
        <div class="row">
          <div class="mx-auto">
            <p>CopyRight Infratop.inc</p>
          </div>
        </div>
      </div>
</footer>

app/views/layouts/_genre_search.html.erb
<!-- @genres → genres -->
<table class="table table-bordered">
  <thead class="table-light">
    <tr>
      <th class="text-center">ジャンル検索</th>
    </tr>
  </thead>
  <tbody>
    <% genres.each do |genre| %>
    <tr>
      <td><%= link_to genre.genre_name, items_path(genre_id: genre.id) %></td>
    </tr>
    <% end %>
  </tbody>
</table>

app/views/layouts/_public_header_template.html.erb
<header class="public mb-5" style="background-color: #e3f2fd;">
  <div class="container">
    <nav class="navbar navbar-expand-lg navbar-light">
      <div class="container">
        <a class="navbar-brand" href="/">ながのCAKE</a>
        <!--ログインしている人の名前を表示-->
        <% if customer_signed_in? %>
          <p class="mb-0 ml-5 align-middle">ようこそ、<%= current_customer.last_name %>さん！</p>
        <% end %>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
          <ul class="navbar-nav ml-auto">
            <% if customer_signed_in? %>
              <li class="nav-item"><%= link_to "マイページ", customers_my_page_path, class: "nav-link" %></li>
              <li class="nav-item"><%= link_to "商品一覧", items_path, class: "nav-link" %></li>
              <li class="nav-item"><%= link_to "カート", cart_items_path, class: "nav-link" %></li>
              <li class="nav-item"><%= link_to "ログアウト", destroy_customer_session_path, method: :delete, class: "nav-link" %></li>
            <% else %>
              <li class="nav-item"><%= link_to "About", about_path, class: "nav-link" %></li>
              <li class="nav-item"><%= link_to "商品一覧", items_path, class: "nav-link" %></li>
              <li class="nav-item"><%= link_to "新規登録", new_customer_registration_path, class: "nav-link" %></li>
              <li class="nav-item"><%= link_to "ログイン", new_customer_session_path, class: "nav-link" %></li>
            <% end %>
          </ul>
        </div>
      </div>
    </nav>
  </div>
  <div class="container"> <!--tableタグ-->
    <div class="col-2 ml-auto d-flex">
      <%= form_with url: items_path, method: :get do |f| %>
        <table>
          <tr>
            <td><%= f.text_field :search, class: "d-inline" %></td>
            <td>
              <button type="submit">
                <i class="fas fa-search"></i>
              </button>
            </td>
          </tr>
        </table>
      <% end %>
    </div>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>NaganoCake</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>